export const evaluations = [
    {
      name: 'Mark Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '2',
      planned: '3',
      achieved: '2',
      comments: '',
      start_time: '17:52:00',
      end_time: '17:53:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: true,
      difference: '1'
    },
    {
      name: 'John Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '5',
      planned: '5',
      achieved: '5',
      comments: 'good',
      start_time: '17:58:00',
      end_time: '17:58:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: true,
      difference: '0'
    },
    {
      name: 'Martin Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'Marie Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'Adam Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'John Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '5',
      planned: '5',
      achieved: '5',
      comments: 'good',
      start_time: '17:58:00',
      end_time: '17:58:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: true,
      difference: '0'
    },
    {
      name: 'Martin Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'Marie Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'Adam Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    }
  ];

  export const evaluationsHeadCells = [
    {
      id: 'name',
      numeric: false,
      label: 'Name',
      tableView: true,
    },
    {
      id: 'title',
      numeric: false,
      label: 'Title',
      tableView: true,
    },
    {
      id: 'quality',
      numeric: true,
      label: 'Quality',
      tableView: false,
    },
    {
        id: 'planned',
        numeric: true,
        label: 'Planned',
        tableView: false,
      }, 
      {
        id: 'achieved',
        numeric: true,
        label: 'Achieved',
        tableView: true,
      },
      {
        id: 'comments',
        numeric: false,
        label: 'Comments',
        tableView: true,
      },
      {
        id: 'start_time',
        numeric: false,
        label: 'Start Time',
        tableView: false,
      },
      {
        id: 'end_time',
        numeric: false,
        label: 'End Time',
        tableView: false,
      },
      {
        id: 'date',
        numeric: false,
        label: 'Date',
        tableView: true,
      },
      {
        id: 'as_planned',
        numeric: true,
        label: 'As Planned',
        tableView: false,
      },
      {
        id: 'difference',
        numeric: true,
        label: 'Difference',
        tableView: true,
      }, 
      
  ];